# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"is_jupyter": "00_core.ipynb",
         "logger": "00_core.ipynb",
         "fig": "00_core.ipynb",
         "jn": "00_core.ipynb",
         "parser": "00_core.ipynb",
         "add_arg": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://miklevin.github.io/seoml/"

git_url = "https://github.com/miklevin/seoml/tree/main/"

def custom_doc_links(name): return None
