# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['is_jupyter', 'logger', 'fig', 'jn', 'parser', 'add_arg']

# Cell
import pickle
import logging
from pyfiglet import Figlet
from argparse import ArgumentParser


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

fig = lambda x: print(Figlet(font="standard", width=200).renderText(x))

# export
def is_jupyter():
    jn = True
    try:
        get_ipython()
    except NameError as err:
        logger.error(err)
        jn = False
    return jn


jn = is_jupyter()
print(jn)

parser = ArgumentParser()
add_arg = parser.add_argument

if jn:
    # simulate command-line input
    with open("./seoml/args.pkl", "rb") as handle:
        args = pickle.load(handle)
else:
    # get input arguments from command-line
    add_arg("-f", "--file", required=True)
    add_arg("-d", "--description", required=False)
    args = parser.parse_args()
    with open("args.pkl", "wb") as handle:
        pickle.dump(args, handle)

print(args)