# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['hello', 'logger', 'is_jupyter']

# Cell
import logging
from pyfiglet import Figlet


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def hello(name):
    return "Hello %s!" % name

# Cell
def is_jupyter():
    jn = True
    try:
        get_ipython()
    except:
        jn = False
    return jn


print(is_jupyter())